investigator_model_name: "/work7/sean/l8b_investigator_toxic_fw1_checkpoints/checkpoint-357"
target_model_name: "Qwen/Qwen2.5-Coder-1.5B-Instruct"
penalise_model_name: "/work7/sean/l8b_penalise_toxic_fw1_checkpoints/checkpoint-357"
lambda: 1 # penalization strength
data_file: "toxic_suffixes_l8b.jsonl"
output_file: "dsft_toxic_l8b.jsonl"
progress_file: "dsft_toxic_l8b_progress.json"
num_candidates: 8       # candidate prefixes per suffix
pairs_per_suffix: 2     # pairs to save per suffix
max_new_tokens: 64
batch_size_suffixes: 8 # suffixes processed in parallel
min_prefix_len: 10 # minimum prefix len we'll keep in dataset
minimum_score_diff: 0.05 # minimum score diff between pairs that we'll accept
device_inv: "cuda:0" # device for investigator
device_target: "cuda:0" # device for target model, for scoring proposed prefixes
device_penalize: "cuda:0" # device for the previous fw model, for