model_name: "output/qwen1b_sft/checkpoint-78"
ref_model_name: "Qwen/Qwen2.5-Coder-1.5B-Instruct"
data_file: "qwen1b/toxic_dpo_qwen1b.jsonl"
output_dir: "qwen1b/investigator_dpo_checkpoints"
device: "cuda"
cuda_visible_devices: "0"